# Generated by Django 4.0.4 on 2022-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PractiseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=40)),
                ('question_level', models.CharField(choices=[('easy', 'EASY'), ('medium', 'MEDIUM'), ('hard', 'HARD'), ('expert', 'EXPERT')], default='easy', max_length=50)),
                ('question_skillreq', models.CharField(choices=[('problem solving (basic)', 'PROBLEM SOLVING (BASIC)'), ('problem solving (intermediate)', 'PROBLEM SOLVING (INTERMEDIATE)'), ('problem solving (advanced)', 'PROBLEM SOLVING (ADVANCED)')], default='problem solving (basic)', max_length=50)),
                ('question_subdomain', models.CharField(choices=[('data structures', 'DATA STRUCTURES'), ('implementation', 'IMPLEMENTATION'), ('search', 'SEARCH'), ('graph theory', 'GRAPH THEORY'), ('dynamic programming', 'DYNAMIC PROGRAMMING'), ('constructive algorithms', 'CONSTRUCTIVE ALGORITHMS'), ('bit manipulation', 'BIT MANIPULATION'), ('recursion', 'RECURSION'), ('debugging', 'DEBUGGING')], default='data structures', max_length=50)),
                ('users_solved', models.IntegerField(editable=False)),
                ('users_tried', models.IntegerField(editable=False)),
                ('question_desc', models.CharField(max_length=1500)),
                ('function_description', models.CharField(max_length=300)),
                ('input_format', models.CharField(max_length=300)),
                ('constraints', models.CharField(max_length=150)),
                ('output_format', models.CharField(max_length=300)),
                ('sample_input', models.CharField(max_length=50)),
                ('sample_output', models.CharField(max_length=50)),
                ('explanation', models.CharField(max_length=200)),
            ],
        ),
    ]
