# Generated by Django 4.0.4 on 2022-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_desc', models.CharField(max_length=30)),
                ('lobby_score', models.IntegerField()),
                ('lobby_users', models.JSONField(default='{}', editable=False)),
            ],
        ),
    ]
