# Generated by Django 4.0.4 on 2022-05-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='lobby_users',
            field=models.JSONField(default={}, editable=False),
        ),
    ]
