# Generated by Django 4.0.4 on 2022-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0003_alter_lobby_lobby_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='lobby_name',
            field=models.CharField(default='uıh', max_length=15),
            preserve_default=False,
        ),
    ]
